# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  auth0_client_id: <%= ENV['AUTH0_CLIENT_ID'] %>
  auth0_client_secret: <%= ENV['AUTH0_CLIENT_SECRET'] %>
  auth0_domain: <%= ENV['AUTH0_DOMAIN'] %>

development:
  <<: *default
  secret_key_base: 804bff40aacd55ba75765792e0e42ce50990f7cc10c8c0789cce777c15bdeb1041d0c90edea293918fd11f6f9ee84957bc4b2ea64c2fe8cb808c1f9c4903c101

test:
  <<: *default
  secret_key_base: c3b34ef76e5be2b48f8d87c163a60b9f6e914f630e0aa6166d2953e7767ef682d4be9b1f5b37ad2575104c00f542c2c144a3c4f8193530ed0ceb2a4909b2497d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
